// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.23.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name, dynamic hint}) =>
    RustLib.instance.api.greet(name: name, hint: hint);

class Example {
  final int number;

  const Example({
    required this.number,
  });

  Future<void> answer({dynamic hint}) => RustLib.instance.api.exampleAnswer(
        that: this,
      );

  static Future<void> boo({dynamic hint}) =>
      RustLib.instance.api.exampleBoo(hint: hint);

  int getNumber({dynamic hint}) => RustLib.instance.api.exampleGetNumber(
        that: this,
      );

  @override
  int get hashCode => number.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Example &&
          runtimeType == other.runtimeType &&
          number == other.number;
}
